apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/restartedAt: "2020-09-30T14:19:12+04:00"
  creationTimestamp: "2020-09-30T10:19:12Z"
  generateName: easy-wallet-56b9cc8887-
  labels:
    app: easy-wallet
    pod-template-hash: 56b9cc8887
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/restartedAt: {}
        f:generateName: {}
        f:labels:
          .: {}
          f:app: {}
          f:pod-template-hash: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"c93be17a-3d52-4cf0-aef7-b87a0012cb4f"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:containers:
          k:{"name":"easy-wallet"}:
            .: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:terminationGracePeriodSeconds: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-09-30T10:19:12Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"172.17.0.5"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    time: "2020-09-30T10:19:14Z"
  name: easy-wallet-56b9cc8887-h2gn8
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: easy-wallet-56b9cc8887
    uid: c93be17a-3d52-4cf0-aef7-b87a0012cb4f
  resourceVersion: "1083"
  selfLink: /api/v1/namespaces/default/pods/easy-wallet-56b9cc8887-h2gn8
  uid: ff2e9c68-3ee0-4b61-a3c5-fccca9aa442f
spec:
  containers:
  - image: docker.io/library/easy-wallet:0.0.1-SNAPSHOT
    imagePullPolicy: IfNotPresent
    name: easy-wallet
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-2kvmr
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-2kvmr
    secret:
      defaultMode: 420
      secretName: default-token-2kvmr
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-09-30T10:19:12Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-09-30T10:19:14Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-09-30T10:19:14Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-09-30T10:19:12Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://79f6253da707ff663d1484e83bdc89106611364c994092080ff8cb2843464cda
    image: easy-wallet:0.0.1-SNAPSHOT
    imageID: docker://sha256:b8dbba465f83405c9d6acefb3470d8cf20e659834b1a5a6b09539a12f1ff28da
    lastState: {}
    name: easy-wallet
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-09-30T10:19:13Z"
  hostIP: 192.168.99.101
  phase: Running
  podIP: 172.17.0.5
  podIPs:
  - ip: 172.17.0.5
  qosClass: BestEffort
  startTime: "2020-09-30T10:19:12Z"